name: maxed

services:
  maxed_db:
    image: postgres:18
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: maxed_db
    volumes:
      - maxed_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - maxed_db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:4.2.1
    restart: always
    ports:
      - "5672:5672"   # port for default AMPQ users
      - "15672:15672" # admin RabbitMQ
      - "61613:61613" # port STOMP (for ChatService)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: /bin/bash -c "rabbitmq-plugins enable rabbitmq_stomp rabbitmq_management && rabbitmq-server"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:8.4.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # UI Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_CORS_ALLOW_ORIGIN: "*"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; do
        echo '...waiting for minio service...' && sleep 1;
      done;
      /usr/bin/mc ls myminio/media > /dev/null 2>&1 || /usr/bin/mc mb myminio/media;
      echo 'MinIO bucket setup complete.';
      exit 0;
      "

volumes:
  maxed_data:
  rabbitmq_data:
  redis_data:
  minio_data:
